# Generated by Django 4.2.5 on 2023-10-08 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('title_esp', models.CharField(default='Apartamento', max_length=100)),
                ('title_eng', models.CharField(default='Apartment', max_length=100)),
                ('title_ru', models.CharField(default='Апартамент', max_length=100)),
                ('title_uk', models.CharField(default='Апартаменти', max_length=100)),
                ('max_person', models.CharField(default='1', max_length=2)),
                ('rooms_amount', models.CharField(default='1', max_length=3)),
                ('is_best_offer', models.BooleanField(default=False)),
                ('has_AirConditioner', models.BooleanField(default=False)),
                ('has_Beach', models.BooleanField(default=False)),
                ('summer_price', models.CharField(default='0', max_length=3)),
                ('rest_of_year_price', models.CharField(default='0', max_length=5)),
                ('description_esp', models.TextField(default='', max_length=1000)),
                ('description_eng', models.TextField(default='', max_length=1000)),
                ('description_ru', models.TextField(default='', max_length=1000)),
                ('description_uk', models.TextField(default='', max_length=1000)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published')),
                ('product_main_image', models.ImageField(default='', upload_to=main.models.Product.get_folder_name)),
                ('is_Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.ProductImage.get_folder_name)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
