# Generated by Django 4.2.5 on 2023-10-23 08:34

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usercontact_email_alter_usercontact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_eng',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание на английском'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_esp',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание на испанком'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание на русском'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uk',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание на украинском'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_AirConditioner',
            field=models.BooleanField(default=False, verbose_name='Есть кондиционер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_Beach',
            field=models.BooleanField(default=False, verbose_name='Есть пляж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_Available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_offer',
            field=models.BooleanField(default=False, verbose_name='Лучшее предложение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_person',
            field=models.CharField(default='1', max_length=2, verbose_name='Макс. человек'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_main_image',
            field=models.ImageField(default='', upload_to=main.models.Product.get_folder_name, verbose_name='ГЛАВНОЕ ФОТО'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rest_of_year_price',
            field=models.CharField(default='0', max_length=5, verbose_name='Цена в остальное время года'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rooms_amount',
            field=models.CharField(default='1', max_length=3, verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summer_price',
            field=models.CharField(default='0', max_length=3, verbose_name='Цена летом'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_eng',
            field=models.CharField(default='Apartment', max_length=100, verbose_name='Заголовок на английском'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_esp',
            field=models.CharField(default='Apartamento', max_length=100, verbose_name='Заголовок на испанком'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(default='Апартамент', max_length=100, verbose_name='Заголовок на русском'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uk',
            field=models.CharField(default='Апартаменти', max_length=100, verbose_name='Заголовок на украинском'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=main.models.ProductImage.get_folder_name, verbose_name='Фото'),
        ),
    ]
