# Generated by Django 4.2.5 on 2023-10-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_description_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_Available',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
