# Generated by Django 4.2.5 on 2023-11-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productsell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsell',
            name='has_AirConditioner',
            field=models.BooleanField(default=False, verbose_name='Есть кондиционер'),
        ),
        migrations.AddField(
            model_name='productsell',
            name='has_Beach',
            field=models.BooleanField(default=False, verbose_name='Есть пляж'),
        ),
    ]
