# Generated by Django 4.2.5 on 2023-11-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productsell_has_airconditioner_productsell_has_beach'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsell',
            name='rooms_amount',
            field=models.CharField(default='1', max_length=3, verbose_name='Кол-во комнат'),
        ),
    ]
